# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/design_simple_poll_intp/design_simple_poll_intp.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp || ORIG_REF_NAME==design_simple_poll_intp}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_processing_system7_0_0/design_simple_poll_intp_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_processing_system7_0_0 || ORIG_REF_NAME==design_simple_poll_intp_processing_system7_0_0}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_axi_dma_0_0/design_simple_poll_intp_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_axi_dma_0_0 || ORIG_REF_NAME==design_simple_poll_intp_axi_dma_0_0}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_ps7_0_axi_periph_0/design_simple_poll_intp_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_ps7_0_axi_periph_0 || ORIG_REF_NAME==design_simple_poll_intp_ps7_0_axi_periph_0}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_rst_ps7_0_100M_0/design_simple_poll_intp_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_rst_ps7_0_100M_0 || ORIG_REF_NAME==design_simple_poll_intp_rst_ps7_0_100M_0}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_axi_mem_intercon_0/design_simple_poll_intp_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_axi_mem_intercon_0 || ORIG_REF_NAME==design_simple_poll_intp_axi_mem_intercon_0}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_xlconcat_0_0/design_simple_poll_intp_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_xlconcat_0_0 || ORIG_REF_NAME==design_simple_poll_intp_xlconcat_0_0}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_xbar_0/design_simple_poll_intp_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_xbar_0 || ORIG_REF_NAME==design_simple_poll_intp_xbar_0}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_axis_data_fifo_0_0/design_simple_poll_intp_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_axis_data_fifo_0_0 || ORIG_REF_NAME==design_simple_poll_intp_axis_data_fifo_0_0}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_auto_pc_0/design_simple_poll_intp_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_auto_pc_0 || ORIG_REF_NAME==design_simple_poll_intp_auto_pc_0}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_auto_pc_1/design_simple_poll_intp_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_auto_pc_1 || ORIG_REF_NAME==design_simple_poll_intp_auto_pc_1}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_auto_us_0/design_simple_poll_intp_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_auto_us_0 || ORIG_REF_NAME==design_simple_poll_intp_auto_us_0}]

# IP: bd/design_simple_poll_intp/ip/design_simple_poll_intp_auto_us_1/design_simple_poll_intp_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==design_simple_poll_intp_auto_us_1 || ORIG_REF_NAME==design_simple_poll_intp_auto_us_1}]

# XDC: bd/design_simple_poll_intp/design_simple_poll_intp_ooc.xdc
